server:
  port: 8081
  address: 127.0.0.1
camel:
  springboot:
    main-run-controller: true
dhis2-to-fhir:
  dhis2:
    base-url: https://dev.paho-dhis2.org/
    username: integration
    password: ${DHIS2_PASSWORD}
    org-unit-id: ${DHIS2_ORG_UNIT_ID}
  fhir:
    server-url: http://localhost:8080/fhir/
    fhir-version: R4
